tareas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("trabajos.urls"))
]

trabajos/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

app_name = 'acc'

urlpatterns = [
    path("", views.index, name="index"),
    path("finalizados", views.finalizados, name="finalizados"),
    path("login", views.login_view, name="login"),
    path("register", views.register_view, name="register"),
    path("logout", views.logout_view, name="logout")
]

trabajos/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.db.models.signals import post_save


class Usuario(AbstractUser):
    pass


class Tps(models.Model):

    users = models.ManyToManyField(
        Usuario,  through='Tpsterminados')
    titulo = models.CharField(max_length=100)

    TECNOLOGIA_DE_LA_FABRICACION = 'TDF'
    MANTENIMIENTO_Y_REPARACION_DE_EQUIPOS = 'MYRDE'
    MAQUINAS_ELECTRICAS_Y_ENSAYOS = 'MEYE'
    SEGURIDAD_E_HIGIENE_INDUSTRIAL = 'SEHI'
    LABORATORIO_DE_ENSAYOS_INDUSTRIALES = 'LDEI'
    INSTALACIONES_INDUSTRIALES = 'II'
    RELACIONES_HUMANAS = 'RH'
    TALLER_DE_ELECTROMECANICA = 'TE'
    ORGANIZACION_INDUSTRIAL = 'OI'
    INSTALACIONES_ELECTRICAS = 'IE'
    EDUCACION_FISICA = 'EF'
    EQUIPOS_Y_APARATOS_DE_MANIOBRA_Y_TRANSPORTE = 'EYADMYT'

    MATERIAS_CHOICES = [
        (TECNOLOGIA_DE_LA_FABRICACION, 'Tecnologia de la fabricación'),
        (MANTENIMIENTO_Y_REPARACION_DE_EQUIPOS, 'Mantenimiento y R de equipos'),
        (MAQUINAS_ELECTRICAS_Y_ENSAYOS, 'Máquinas eléctricas y ensayos'),
        (SEGURIDAD_E_HIGIENE_INDUSTRIAL, 'Seguridad e higiene industrial'),
        (LABORATORIO_DE_ENSAYOS_INDUSTRIALES,
         'Laboratorio de ensayos industriales'),
        (INSTALACIONES_INDUSTRIALES, 'Instalaciones industriales'),
        (RELACIONES_HUMANAS, 'Relaciones humanas'),
        (TALLER_DE_ELECTROMECANICA, 'Taller de electromecánica'),
        (ORGANIZACION_INDUSTRIAL, 'Organización industrial'),
        (INSTALACIONES_ELECTRICAS, 'Instalaciones eléctricas'),
        (EDUCACION_FISICA, 'Educacion fisica'),
        (EQUIPOS_Y_APARATOS_DE_MANIOBRA_Y_TRANSPORTE,
         'Equipos y aparatos de maniobra y transporte')
    ]
    materia = models.CharField(
        max_length=8, choices=MATERIAS_CHOICES, default=None)

    fecha_actual = models.DateField(default=timezone.now)
    fecha_entrega = models.DateField(auto_now=False, auto_now_add=False)

    material = models.URLField()
    consignas = models.URLField()

    class Meta:
        ordering = ('-fecha_entrega',)

    def __str__(self):
        return self.titulo


def taskdone(sender, instance, **kwargs):
    for user in Usuario.objects.all():
        if not Tpsterminados.objects.filter(user=user, tps=Tps.objects.last()):
            Tpsterminados.objects.create(user=user, tps=Tps.objects.last())


post_save.connect(taskdone, sender=Tps)


class Tpsterminados(models.Model):
    user = models.ForeignKey(Usuario, on_delete=CASCADE)
    tps = models.ForeignKey(Tps, on_delete=CASCADE)
    status = models.BooleanField(default=True)

trabajos/views.py
from django.contrib.auth.models import User
from django.http.response import StreamingHttpResponse
from django.shortcuts import redirect, render
from django.db import IntegrityError, utils
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import datetime

from .models import Tpsterminados, Usuario, Tps


def index(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            trabajos = Tpsterminados.objects.filter(
                status=True, user=request.user)

            date = datetime.date.today()

            Tpfecha = Tps.objects.all()

            for tp in Tpfecha:
                if tp.fecha_entrega < date:
                    Tpsterminados.objects.filter(tps=tp).update(status=False)

            return render(request, "usuario/index.html", {
                'trabajos': trabajos
            })

        elif request.method == 'POST':
            trabajoid = request.POST['id']
            Tpsterminados.objects.filter(id=trabajoid).update(status=False)
            return HttpResponseRedirect(reverse('acc:index'))

    else:
        return HttpResponseRedirect(reverse('acc:login'))


def finalizados(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            trabajos = Tpsterminados.objects.filter(
                status=False, user=request.user)
            return render(request, "usuario/finalizados.html", {
                'trabajos': trabajos
            })
        else:
            trabajoid = request.POST['id']
            Tpsterminados.objects.filter(id=trabajoid).update(status=True)
            return HttpResponseRedirect(reverse("acc:index"))


def login_view(request):
    # Muestra la pagina si es solicitada con un GET
    if request.method == "GET":
        return render(request, "usuario/login.html")

    # cuando un post es enviado
    else:
        # guarda los datos del usuario en variables
        username = request.POST["username"]
        password = request.POST["password"]

        # compara los datos enviados por el post con los que hay en la base de datos
        user = authenticate(request, username=username, password=password)

        # si los datos coinciden, logea al usuario y lo redirecciona al index
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("acc:index"))

        # sino los manda al login (agregar mensaje de error!!!)
        else:
            error = 'erraste wachin'
            return render(request, "usuario/login.html", {
                'mensaje': error
            })


def logout_view(request):
    # cierra la sesion
    logout(request)
    return HttpResponseRedirect(reverse('acc:login'))


def register_view(request):
    # guarda los datos enviados a traves del post en variables
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        # checkea si la contraseña es igual a la confirmacion (agregar mensaje de error!!!)
        if password != confirmation:
            return render(request, "usuario/register.html")

        # va a intentar crear un nuevo usuario
        try:
            user = Usuario.objects.create_user(username, email, password)
            user.save()
            for tp in Tps.objects.all():
                Tpsterminados.objects.create(user=user, tps=tp)

        # si el nombre esta en uso tira un error (agregar mensaje de error!!)
        except IntegrityError:
            return render(request, "usuario/register.html")

        # si el usuario es registrado, lo logea
        login(request, user)
        return HttpResponseRedirect(reverse('acc:index'))

    else:
        return render(request, "usuario/register.html")

trabajos/templates/usuario/finalizados.html
{% extends "usuario/indexlayout.html" %}

{% load static %}

{block titile} Trabajos Pendientes {endblock}

{% block css %}
<link rel="stylesheet" href="{% static 'usuario/index.css' %}">
<script src="{% static 'usuario/index.js' %}"></script>
{% endblock %}

{% block body%}
  
  <div class="tarjeta-contenedor">
    {% for trabajo in trabajos %}
    <div class="tarjeta-wrapper">
      <div class="tarjeta">
        <div class="title">
          <h1>{{ trabajo.tps.titulo }}</h1>
        </div>
        <div class="materia">
          <h3>{{ trabajo.tps.get_materia_display }}</h3>
        </div>
        <div class="entrega">
          <h3>Fecha de entrega: {{ trabajo.tps.fecha_entrega }}</h3>
        </div>
        <div class="botones">
          <button type="button" class="boton" id="boton1">
            <a href="{{ trabajo.tps.consignas }}">Consignas</a>
          </button>
          <button type="button" class="boton" id="boton2">
            <a href="{{ trabajo.tps.material }}">Material</a>
          </button>
        </div>
      </div>
      <div class="activo">
        <form action="/finalizados" method="POST" class="form">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ trabajo.id }}">
            <button onclick="desaparecer()" type="submit" class="entregado" id="pendiente">
                Marcar como pendiente
              </button>
        </form>

      </div>
    </div>

    {% empty %}
    <style>
      .tarjeta-contenedor{
        display: flex;
        justify-content: space-evenly;
        flex-direction: column;
      }
    </style>
    <div class="empty-container">
      <h1 class="empty">¡No finalizaste ningun trabajo!</h1>
      <p class="empty-p">Probablemente tengas <a href="{% url 'acc:index' %}">Trabajos Pendientes</a></p>
    </div>

    {% endfor %}
  </div>

{% endblock %}

trabajos/templates/usuario/index.html
{% extends "usuario/indexlayout.html" %}

{% load static %}

{block titile} Trabajos Pendientes {endblock}

{% block css %}
<link rel="stylesheet" href="{% static 'usuario/index.css' %}">
<script src="{% static 'usuario/index.js' %}"></script>
{% endblock %}

{% block body%}
  <div class="tarjeta-contenedor">
    {% for trabajo in trabajos %}
    <div class="tarjeta-wrapper">
      <div class="tarjeta">
        <div class="title">
          <h1 class="t">{{ trabajo.tps.titulo }}</h1>
        </div>
        <div class="materia">
          <h3>{{ trabajo.tps.get_materia_display }}</h3>
        </div>
        <div class="entrega">
          <h3>Fecha de entrega: {{ trabajo.tps.fecha_entrega }}</h3>
        </div>
        <div class="botones">
          <button type="button" class="boton" id="boton1">
            <a href="{{ trabajo.tps.consignas }}">Consignas</a>
          </button>
          <button type="button" class="boton" id="boton2">
            <a href="{{ trabajo.tps.material }}">Material</a>
          </button>
        </div>
      </div>
      <div class="activo">
        <form action="/" method="POST" class="form">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ trabajo.id }}">
          <button onclick="desaparecer()" type="submit" class="entregado">
              Marcar como finalizado
            </button>
      </form>
      </div>
    </div>
    
  {% empty %}
  <style>
    .tarjeta-contenedor{
      flex-wrap: nowrap;
      flex-direction: column;
    }
  </style>
  <div class="empty-container" id="empty-index">
    <h1 class="empty">¡Estas al dia!</h1>
    <p class="empty-p">No tenes ningun trabajo pendiente</p>

  </div>
    {% endfor %}

  </div>







{% endblock %}

trabajos/templates/usuario/indexlayout.html
{% load static %}
<!DOCTYPE html>

<html lang ="es">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'usuario/index.css' %}" rel="stylesheet">
        {% block css %}{% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'acc:index' %}">Trabajos Pendientes</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'acc:finalizados' %}">Trabajos Finalizados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Horarios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'acc:logout' %}">Cerrar sesión</a>
                </li>
                </ul>
            </div>
        </nav>





        {% block body %}
        {% endblock %}


        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>

</html>

trabajos/templates/usuario/layout.html
{% load static %}
<!DOCTYPE html>

<html lang ="es">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'usuario/styles.css' %}" rel="stylesheet">
        {% block css %}{% endblock %}
    </head>
    <body>

        <header class="head-wrapper">
            {% block header %}{% endblock %}
        </header>


        <div class="contenedor">
            <div class="form">
                {% block body %}
                {% endblock %}
            </div>
        </div>

        

    </body>

</html>

trabajos/templates/usuario/login.html
{% extends "usuario/layout.html" %}


{% load static %}

{block titile} Iniciar sesion {endblock}

{% block css %}
<link rel="stylesheet" href="{% static 'usuario/forms.css' %}">
{% endblock %}

{% block header%}

<div class="head">
    <a href="{% url 'acc:register' %}" class="opcion">Registrarse
        <img class="flecha" src="{% static 'usuario/flecha2.svg' %}">
    </a>
</div>

{% endblock %}

{% block body %}



<div class="text">
    <h2>Iniciar sesión</h2>

</div>

{{mensaje}}


<div class="login">
    <form action="/login" method="POST" autocomplete="off">
        {% csrf_token %}
        <div class="wrapper">
            <div class="input">
                <input class="field" type="text" name="username" placeholder="Nombre de usuario" autocomplete="off">
            </div>
            <div class="input">
                <input class="field"type="password" name="password" placeholder="Contraseña">
            </div>
        </div>
            <div class="boton">
                <input type="submit" value="Iniciar sesión" class="button"> 
            </div>
    </form>
</div>

{% endblock %}

trabajos/templates/usuario/register.html
{% extends "usuario/layout.html" %}

{% load static %}

{block titile} Registrarse {endblock}

{% block css %}
<link rel="stylesheet" href="{% static 'usuario/forms.css' %}">
{% endblock %}

{% block header%}

<div class="head">
    <a href="{% url 'acc:login' %}" class="opcion">Iniciar Sesión
        <img class="flecha" src="{% static 'usuario/flecha2.svg' %}">
    </a>
</div>

{% endblock %}

{% block body %}



<div class="text">
    <h2>Registrarse</h2>

</div>


<div class="login">
    <form action="/register" method="POST">
        {% csrf_token %}
        <div class="wrapper">
            <div class="input">
                <input class="field" type="text" name="username" placeholder="Nombre de usuario">
            </div>
            <div class="input">
                <input class="field" type="text" name="email" placeholder="Correo electronico">
            </div>
            <div class="input">
                <input class="field"type="password" name="password" placeholder="Contraseña">
            </div>
            <div class="input">
                <input class="field"type="password" name="confirmation" placeholder="Confirmar contraseña">
            </div>
        </div>
            <div class="boton">
                <input type="submit" value="Registrarse" class="button"> 
            </div>
    </form>
</div>

{% endblock %}